apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: default
  labels:
    app: fastapi
spec:
  selector:
    app: fastapi
  ports:
    - name: http          # add this
      port: 80
      targetPort: 8000
  type: ClusterIP