apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: fastapi
  endpoints:
    - port: http          # name, not number
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s